### ISSUE TITLE
kernel 3.19.1 kernel/built-in.o 

### ISSUE THREAD

**Issue by satyapendem** [beagleboard/linux#100]
*_kernel/built-in.o : In function 'do_adjtimex' (.text+0x5020e): undefined reference to '__do_adjtimex any plz help with that i'm trying to make linux 3.19 to 3.19.1
![capture](https://cloud.githubusercontent.com/assets/14092224/18033052/489d0264-6d36-11e6-9f04-41f57d9f10e9.JPG)
*_

**Comment by RobertCNelson** [comment]
Active support is on the 4.4 branch

Regards,

**Comment by satyapendem** [comment]
thank you.
