### ISSUE TITLE
Error installing MySQL

### ISSUE THREAD

**Issue by rob0795** [beagleboard/linux#129]
Hello,
I tried installing mysql database en the beaglebone black Debian 8 but i got the next error:

`root@beaglebone:~# apt-get install mysql-server mysql-client`
`Reading package lists... Done`
`Building dependency tree`
`Reading state information... Done`
`mysql-client is already the newest version.`
`mysql-server is already the newest version.`
`0 upgraded, 0 newly installed, 0 to remove and 173 not upgraded.`
`2 not fully installed or removed.`
`After this operation, 0 B of additional disk space will be used.`
`Do you want to continue? [Y/n] y`
`Setting up mysql-server-5.5 (5.5.55-0+deb8u1) ...`
`Job for mysql.service failed because the control process exited with error code.`
`See "systemctl status mysql.service" and "journalctl -xe" for details.`
`invoke-rc.d: initscript mysql, action "start" failed.`
`dpkg: error processing package mysql-server-5.5 (--configure):`
` subprocess installed post-installation script returned error exit status 1`
`dpkg: dependency problems prevent configuration of mysql-server:`
` mysql-server depends on mysql-server-5.5; however:`
`  Package mysql-server-5.5 is not configured yet.`
`  `
`dpkg: error processing package mysql-server (--configure):`
` dependency problems - leaving unconfigured`
`Errors were encountered while processing:`
` mysql-server-5.5`
` mysql-server`
`E: Sub-process /usr/bin/dpkg returned an error code (1)`

Then I get the following output:

`root@beaglebone:~# systemctl status mysql.service`
`● mysql.service - LSB: Start and stop the mysql database server daemon`
`   Loaded: loaded (/etc/init.d/mysql; generated; vendor preset: enabled)`
`   Active: failed (Result: exit-code) since Tue 2017-07-18 21:16:01 UTC; 3min 25s ago`
`     Docs: man:systemd-sysv-generator(8)`
`  Process: 3547 ExecStart=/etc/init.d/mysql start (code=exited, status=1/FAILURE)`
`  `
`Jul 18 21:15:21 beaglebone systemd[1]: Starting LSB: Start and stop the mysql database server daemon...`
`Jul 18 21:16:01 beaglebone /etc/init.d/mysql[4573]: 0 processes alive and '/usr/bin/mysqladmin --defaults-file=/etc/mysql/debian.cnf ping' resulted in`
`Jul 18 21:16:01 beaglebone mysql[3547]: Starting MySQL database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!`
`Jul 18 21:16:01 beaglebone systemd[1]: mysql.service: Control process exited, code=exited status=1`
`Jul 18 21:16:01 beaglebone systemd[1]: Failed to start LSB: Start and stop the mysql database server` `daemon.`
`Jul 18 21:16:01 beaglebone systemd[1]: mysql.service: Unit entered failed state.`
`Jul 18 21:16:01 beaglebone systemd[1]: mysql.service: Failed with result 'exit-code'.`

I tried stopping and starting again the service but get the same mistake. I'm newbie at Linux so I would really aprecciare some help. Thanks.

**Comment by RobertCNelson** [comment]
@rob0795 closing issue, this is not a kernel issue.

You already have a reply to your original question:

https://groups.google.com/d/msg/beagleboard/n1YNzSKuWtI/42FQGIFrBwAJ

please keep all comments at the same location.

Regards,
