### ISSUE TITLE
PocketBeagle device tree entries for CAN0 missing

### ISSUE THREAD

**Issue by derekmulcahy** [beagleboard/linux#143]
Installation from bone-debian-9.2-console-armhf-2017-10-12-2gb.img.xz with kernel 4.9.54-ti-r68.

`sudo config-pin P1.26 can`

returns

`Cannot write pinmux file: /sys/devices/platform/ocp/ocp:P1_26_pinmux/state`

In the device tree I see pinmux entries for CAN1 on P2_9, P2_11 and P2_25, P2_27 but nothing similar for P1_26, P1_28 to support CAN0.

**Comment by RobertCNelson** [comment]
@derekmulcahy this was added in 4.9.59-ti-r73, so feel free to upgrade:

https://github.com/RobertCNelson/ti-linux-kernel-dev/commits/ti-linux-4.9.y

Regards,

**Comment by derekmulcahy** [comment]
Thanks, that worked!
