### ISSUE TITLE
Incorrect definition of SLEWCTRL_FAST in include/dt-bindings/pinctrl/am33xx.h

### ISSUE THREAD

**Issue by chdh** [beagleboard/linux#16]
The following definition in [am33xx.h](https://github.com/beagleboard/linux/blob/3.14/include/dt-bindings/pinctrl/am33xx.h) is wrong:

    #define SLEWCTRL_FAST           (1 << 6)

A correct definition would be:

    #define SLEWCTRL_FAST           (0 << 6)      /* dummy, fast is default */
    #define SLEWCTRL_SLOW           (1 << 6)

References:

1) It was correct in the Rowboat kernel: [mux.h](https://gitorious.org/rowboat/kernel/source/03f2a1e9ea7f8b11ff6809f5a75b614011f8adb6:arch/arm/mach-omap2/mux.h):

    #define AM33XX_SLEWCTRL_FAST            (0 << 6)
    #define AM33XX_SLEWCTRL_SLOW            (1 << 6)

2) [AM335x Technical Reference Manual](http://www.ti.com/lit/ug/spruh73k/spruh73k.pdf)

Section "9.2.2 Pad Control Registers": Bit 6 SLEWCTRL: 0 = Fast, 1 = Slow
Section "9.3.1.50 `conf_<module>_<pin>` Register": Bit 6, Field `conf_<module>_pin_slewctrl`: Select between faster or slower slew rate. 0 = Fast, 1 = Slow.
 
3) meta-ti message from Peter A. Bigot: ["mis-definition of SLEWCTRL_FAST in dt-bindings amxxxx header"](https://lists.yoctoproject.org/pipermail/meta-ti/2014-September/005211.html) 

4) TI forum discussion: [AM335x Slew rate setup in the device tree](http://e2e.ti.com/support/arm/sitara_arm/f/791/p/367445/1382229)

5) It's not fixed at [kernel.org](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/include/dt-bindings/pinctrl/am33xx.h)

**Comment by RobertCNelson** [comment]
http://git.ti.com/gitweb/?p=ti-linux-kernel/ti-linux-kernel.git;a=commit;h=945e20d2734db817bcacd18f71acfb2389805e06
