### ISSUE TITLE
am335x-boneblack-emmc-overlay.dtb missing in 4.14.36-ti-r45

### ISSUE THREAD

**Issue by floion** [beagleboard/linux#161]
Hi,
is there a new overlay to be used in 4.14.36-ti-r45 instead of am335x-boneblack-emmc-overlay.dtb which is missing from this kernel version?

Thanks

**Comment by RobertCNelson** [comment]
@floion these custom dtb files was replaced in v4.14.x genericlly via u-boot overlays, in your case set this in /boot/uEnv.txt

```
enable_uboot_overlays=1
disable_uboot_overlay_video=1
```

https://elinux.org/Beagleboard:BeagleBoneBlack_Debian#U-Boot_Overlays

Regards
