### ISSUE TITLE
4_14 RT  ktimersoftd+  high CPU load

### ISSUE THREAD

**Issue by patrickpoirier51** [beagleboard/linux#166]
Tried on both  --ti-rt-channel --lts-4_14 and --bone-rt-kernel --lts-4_14
Tested both PocketBeagle and BBGreen
getting 62.2% cpu load with top ==    62.2  0.0  35:31.06 ktimersoftd+
ps axo pid,class,rtprio,comm | grep ktimersoft   ==  8 FF       1 ktimersoftd/0

Is this related to "timers: Don't wake ktimersoftd on every tick" ?

**Comment by patrickpoirier51** [comment]
fixed with 4.19.14-bone-rt-r18

**Comment by hitmoon** [comment]
@patrickpoirier51 
Can you tell me:
1) How do you solve this problem ?
2) What is the root cause ?
