### ISSUE TITLE
bone-rt-kernel --lts-4_9    missing cpufreq on PocketBeagle

### ISSUE THREAD

**Issue by patrickpoirier51** [beagleboard/linux#167]
Following the 4_14  cpu load issue https://github.com/beagleboard/linux/issues/166

I reverted back to 4_9 and loaded sudo apt install cpufrequtils
When doing cpufreq-info I get this:
cpufrequtils 008: cpufreq-info (C) Dominik Brodowski 2004-2009
Report errors and bugs to cpufreq@vger.kernel.org, please.
analyzing CPU 0:
  no or unknown cpufreq driver is active on this CPU
  maximum transition latency: 0.00 ms.

Its seems to be into kernel:
 zcat /proc/config.gz | grep CONFIG_CPU_FREQ
CONFIG_CPU_FREQ=y
CONFIG_CPU_FREQ_GOV_ATTR_SET=y
CONFIG_CPU_FREQ_GOV_COMMON=y
CONFIG_CPU_FREQ_STAT=y
CONFIG_CPU_FREQ_STAT_DETAILS=y
CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE=y
# CONFIG_CPU_FREQ_DEFAULT_GOV_POWERSAVE is not set
# CONFIG_CPU_FREQ_DEFAULT_GOV_USERSPACE is not set
# CONFIG_CPU_FREQ_DEFAULT_GOV_ONDEMAND is not set
# CONFIG_CPU_FREQ_DEFAULT_GOV_CONSERVATIVE is not set
CONFIG_CPU_FREQ_GOV_PERFORMANCE=y
CONFIG_CPU_FREQ_GOV_POWERSAVE=y
CONFIG_CPU_FREQ_GOV_USERSPACE=y
CONFIG_CPU_FREQ_GOV_ONDEMAND=y
CONFIG_CPU_FREQ_GOV_CONSERVATIVE=y

But it is not mapped:
ls /sys/devices/system/cpu/cpu0/
crash_notes  crash_notes_size  of_node  power  subsystem  topology  uevent
There is no cpufreq

here is the same SD installed on a BBBlue
ls /sys/devices/system/cpu/cpu0/
cpufreq  crash_notes  crash_notes_size  of_node  power  subsystem  topology  uevent
There is cpufreq

**Comment by RobertCNelson** [comment]
This should be fixed. (kernel dtb bug)

```
sudo /opt/scripts/tools/version.sh
```

**Comment by jadonk** [comment]
did you do 
```sh
cd /opt/scripts
git pull
sudo tools/version.sh
```
first?

**Comment by patrickpoirier51** [comment]
Jason , if you read the above, it wrote t; the file is there and it gets executed, there is just No Result
