### ISSUE TITLE
Patch missing for musb_cppi41.c in 3.14 branch

### ISSUE THREAD

**Issue by chdh** [beagleboard/linux#18]
The patch "[usb: musb: Ensure that cppi41 timer gets armed on premature DMA TX irq](https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/drivers/usb/musb/musb_cppi41.c?h=linux-3.14.y&id=a5d6bd2499fb860e7eaa537973fddcc9d8157491)" is missing for musb_cppi41.c in the 3.14 branch, while newer and older patches have been applied.

**Comment by RobertCNelson** [comment]
It might just be a miss merge:

Pinging Dan: http://git.ti.com/gitweb/?p=ti-linux-kernel/ti-linux-kernel.git;a=commitdiff;h=d34a808ddba13e47ecebaee0aaf668841e667aef

Regards,
