### ISSUE TITLE
Enable remote debugging with CONFIG_OABI_COMPAT

### ISSUE THREAD

**Issue by masoudr** [beagleboard/linux#181]
Hi,
I'm trying to setup remote debugging using Linaro cross toolchains. I compiled a sample code with debug symbols and transfer the output to Beaglebone. Then I open gdbserver on target device and the remote debug on the host with `arm-linux-gnueabihf-gdb ./out_sample` and after connection to the remote device with `target remote` I get this error:

> Reading /lib/ld-linux-armhf.so.3 from remote target...
> Reading symbols from target:/lib/ld-linux-armhf.so.3...Reading /lib/ld-2.23.so from remote target...
> Reading /lib/.debug/ld-2.23.so from remote target...
> (no debugging symbols found)...done.
> 0xb6fd79c0 in ?? () from target:/lib/ld-linux-armhf.so.3
> (gdb) continue 
> Continuing.
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0xb6fd9dde in ?? () from target:/lib/ld-linux-armhf.so.3
> 

I tried [this reference](https://github.com/raspberrypi/linux/issues/766) and enabled `CONFIG_OABI_COMPAT` in my kernel config and transferred new `zImage` to my rootfs. But I still get this error.
This problem can be fixed by compiling the app with static, but on remote debug it should not give this error, Is there any way to I check if OABI has been enabled in the kernel in userspace?

**Comment by RobertCNelson** [comment]
@masoudr yeah CONFIG_OABI_COMPAT is not the answer.  Using Linaro for this is just asking for trouble.

All released kernel images *.deb file are built on a native platform with a match distro. So Debian Stretch linux-image*.deb file is built in Debian Stretch.  Thus if you want to debug the kernel, use the a matching x86 system with the matching lib*:armhf packages installed.

Regards,
