### ISSUE TITLE
Unable to connect to 192.168.7.2 beaglebone board rev c from ubuntu host

### ISSUE THREAD

**Issue by Vikash082** [beagleboard/linux#182]
I am unable to browse my beagleboard from the browser at Ubuntu host as mentioned in Step 3 here https://beagleboard.org/getting-started#step3 . 

I have connected my board through USB and accessing  it through serial console.

The board got the ip 192.168.7.2

I have updated udev rules using the driver provider (mkdevrules.sh).

The interface which appears corresponding to USB of beagleboard didn't got the IP by default. So, I assigned 192.168.7.1 manually on host interface, but still the board is not reachable.

My host is running Ubuntu 18.04.
And the kernel version:
```
$uname -msr
Linux 4.15.0-32-generic x86_64
```

Other steps I have followed on host is:
- iptables -F
- service ufw stop

But none of them helped.

Do, I need to install any other driver or need to do any other configuration ?

**Comment by jadonk** [comment]
On my Ubuntu 18.04 image, the board shows up automatically, but the interface is disabled by default. There is a pull-down on the top-right listing off the new "Ethernet" interfaces provided and you must enable one of them. One will give you 192.168.6.1 and the other will give you 192.168.7.1.
