### ISSUE TITLE
possible rpmsg breakage in v4.14 stable

### ISSUE THREAD

**Issue by dlech** [beagleboard/linux#184]
FYI, I had to revert https://github.com/beagleboard/linux/commit/1ed3a93072307265d6385031b72929a904b50f87 because it broke my out of tree rpmsg driver. `dev_pm_domain_attach()` returns `-ENODEV` if there is not a device tree node associated with the rpmsg device, which is always going to be the case when dealing with PRU remoteproc. So, it would probably be a good idea to revert in in the bb.org kernel as well.

**Comment by RobertCNelson** [comment]
thanks @dlech i'll revert it asap!
