### ISSUE TITLE
issue in enabling SPI in debian 9

### ISSUE THREAD

**Issue by akashlad007** [beagleboard/linux#193]
Hello,
I am also using  debian release i.e. debian 4.14.71-ti-r80. I am facing problem of enabling the SPI bus. As whenever i am writing to my uEnv.txt file the entire system gets corrupted and i have to burn the image again. Also i have a spi test code in c it gets compiled using gcc but whenever i run it using ./spidev_test -D /dev/spidev1.0 this command i get output as: can't open device: No such file or directory Aborted. 

Is there any specific way for the new release of debian that the spi can be enabled. I have read of config-pin but i am not sure of how it is to be implemented can it be explained illustratively.

Thanks.

**Comment by RobertCNelson** [comment]
@akashlad007 , okay that is not normal..

How exactly are you writing to /boot/uEnv.txt that the whole system ends up being corrupted?

Just use nano:

sudo nano /boot/uEnv.txt

and use "ctrl-x" - "y" to save and exit..

Otherwise what changes are you making???

Regards,

**Comment by pdp7** [comment]
@RobertCNelson I see you applied an upstream fix.  Should this be closed?

**Comment by RobertCNelson** [comment]
Unrelated, GitHub automatically does this from time to time.

No response from user, so should be closed anyways.
