### ISSUE TITLE
no gfs2 in 4.14 branch?

### ISSUE THREAD

**Issue by moosbaue** [beagleboard/linux#194]
Hello

I am running a pacemaker cluster on 2 BBB's with 4.4.145-bone23. Tried going to 4.14. At least in 4.14.93-bone17 there is no gfs2 support. Is this intentional? What bare the plans for 4.19

Thank you
Josef

**Comment by RobertCNelson** [comment]
@moosbaue, sorry about that, it got removed in a fs cleanup, i'll add CFS2 as a hard default, should be pushed out to all kernels by mid week. (v4.4.x+ -> 5.1.0-rc1)

```code
CONFIG_GFS2_FS=m
CONFIG_GFS2_FS_LOCKING_DLM=y
```

Regards,

**Comment by moosbaue** [comment]
Thank you Nelson

Saves me from (cross)building kernels myself
I appreciate this very much

kind regards
Josef

-----Original Message-----

Date: Sun, 17 Mar 2019 18:20:24 -0700
Subject: Re: [beagleboard/linux] no gfs2 in 4.14 branch? (#194)
Cc: Josef Moosbauer <josef@moosbauer.net>, Mention <mention@noreply.github.com>
To: beagleboard/linux <linux@noreply.github.com>
Reply-to: beagleboard/linux <reply+00057d36f286aca5df3cce547e532b156a609fc738ab111b92cf0000000118a6
b45892a169ce19249d05@reply.github.com>
From: Robert Nelson <notifications@github.com>
@moosbaue, sorry about that, it got removed in a fs cleanup, i'll add CFS2 as a hard default,
should be pushed out to all kernels by mid week. (v4.4.x+ -> 5.1.0-rc1)

CONFIG_GFS2_FS=m
CONFIG_GFS2_FS_LOCKING_DLM=y

Regards,


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"en
tity":{"external_key":"github/beagleboard/linux","title":"beagleboard/linux","subtitle":"GitHub
repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png
","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","actio
n":{"name":"Open in
GitHub","url":"https://github.com/beagleboard/linux"}},"updates":{"snippets":[{"icon":"PERSON","mes
sage":"@RobertCNelson in #194: @moosbaue, sorry about that, it got removed in a fs cleanup, i'll
add CFS2 as a hard default, should be pushed out to all kernels by mid week. (v4.4.x+ -\u003e
5.1.0-
rc1)\r\n\r\n```code\r\nCONFIG_GFS2_FS=m\r\nCONFIG_GFS2_FS_LOCKING_DLM=y\r\n```\r\n\r\nRegards,\r\n"
}],"action":{"name":"View
Issue","url":"https://github.com/beagleboard/linux/issues/194#issuecomment-473737289"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/beagleboard/linux/issues/194#issuecomment-473737289",
"url": "https://github.com/beagleboard/linux/issues/194#issuecomment-473737289",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
-- 

kind regards / mit freundlichen Grüßen

Moosbauer Josef

<josef@moosbauer.net>

GPG Fingerprint 6748 9413 0EF1 5B23 D707  DBFA 570B 00E3 4689 8CC9

"Of course I'm crazy, but that doesn't mean I'm wrong.I'm mad but not ill"
