### ISSUE TITLE
p8.43 (SYS_BOOT) value

### ISSUE THREAD

**Issue by flightxgf** [beagleboard/linux#198]
Hello, Robert, when the system is up, I tried all kinds of methods but could not get the value of the p8.43(SYS_BOOT) button, may I ask what I should do? 
I wonder how to get the status of pin p8.43 (SYS_BOOT) when the system is up?
Thanks。

**Comment by RobertCNelson** [comment]
@flightxgf , use config-pin on the P8.43 and set as input, and just read it..

Regards,
