### ISSUE TITLE
looking for linux-headers-4.4.30-ti-r64_1jessie_armhf.deb

### ISSUE THREAD

**Issue by michael1888** [beagleboard/linux#200]
Hi beagleboard/linux,

I tried to install 3rd-part software package on debian 8.6 with beaglebone black. However, it is missing /lib/module/4.4.30-ti-r64/build directory, therefore, I am looking for linux-headers-4.4.30-ti-r64_1jessie_armhf.deb

according to https://groups.google.com/forum/#!topic/beagleboard/82th72jb5F8, the file was stored @ http://repos.rcn-ee.net/debian/pool/main/l/linux-upstream/linux-headers-4.4.30-ti-r64_1jessie_armhf.deb

but it is no longer exist any more.

Please kindly advise where I can locate linux-headers-4.4.30-ti-r64_1jessie_armhf.deb

thanks in advance,

Michael

**Comment by RobertCNelson** [comment]
@michael1888 re-uploaded from cold storage to apt repo..
