### ISSUE TITLE
Can not find uEnv.txt file

### ISSUE THREAD

**Issue by anhptvt1992** [beagleboard/linux#222]
Hi all!
I got the issue after finishing loading new OS.
I built new kernel header for my beaglebone black board.
After finishing for loading new OS, I cannot find uEnv.txt file.
I follow this link for update my OS kernel:
http://www.bootembedded.com/beagle-bone-black/building-embedded-linux-system-using-mainline-kernel-for-beaglebone-black/
My u-boot version is v2019.04 and my kernel linux version is : 4.14.108-ti-r124
Please help me for this issue!
Hope to see your feeback!

**Comment by RobertCNelson** [comment]
Please keep conversations in the same place..

https://forum.digikey.com/t/cannot-find-uenv-txt-beaglebone-black-board/4922/2
