### ISSUE TITLE
How to do make config without bb.org_defconfig

### ISSUE THREAD

**Issue by adyjs** [beagleboard/linux#264]
Hi, I am new to this,
I clone the newest version of this repository, then I can not found the "bb.org_defconfig" in arch/arm/configs directory,
and I check the git diff logs, I found it had been remove in master branch, 
may I ask why?

and then, how do I do the default config in master branch version, or must go back to the version which got bb.org_defconfig?
thank you.

**Comment by RobertCNelson** [comment]
What branch are you on?

**Comment by akhilelamadu** [comment]
@adyjs You where able to find a solution for the problem?
