### ISSUE TITLE
PREEMPTive Image

### ISSUE THREAD

**Issue by CodeOn-ArK** [beagleboard/linux#270]
If an Image is compiled with PREEMPT feature, then does that makes the kernel real time?Why is PREEMPT turned on on most distros these days.

**Comment by RobertCNelson** [comment]
No... PREEMPT alone does not mean real time..

The Real Time patchset is still slowly being developed and merged into Linux..

PREEMPT_RT = Real Time..

https://wiki.linuxfoundation.org/realtime/start

Regards,
