### ISSUE TITLE
Pin 104 claimed by MMC1

### ISSUE THREAD

**Issue by traversjames** [beagleboard/linux#44]
In am335x-bone-common.dtsi pin 104 is being claimed by the MMC1 device even though it is not associated with the SDcard connector on the board schematic:
			0x1A0 (PIN_INPUT_PULLUP | MUX_MODE7)	/* mcasp0_aclkr.gpio3_18 */

This is introduced in a8d5991f00ce111e24d74abe802eccb0638deb94 where all mmc pins are initially assigned.

A guess as to why this happened is maybe confusion of the CD pin (gpio0_6) with gpio0_7. gpio0_7 is tied to this gpio3_18 pin on the board on P9_42 so maybe both pins were claimed to avoid conflict.  It doesn't seem necessary and claims a useful PRU/Mcasp resource.

**Comment by jadonk** [comment]
Since that patch seems to be signed-off by several TI folks, can you send a note to the Beagle mailing list (http://beagleboard.org/discuss) and CC them? I wouldn't want to fix it without knowing why they put it in and then not having it fixed everywhere.

**Comment by traversjames** [comment]
Done:
https://groups.google.com/forum/embed/?place=forum/beagleboard&showsearch=true&showpopout=true&showtabs=true&hideforumtitle=true&parenturl=http%3A%2F%2Fbeagleboard.org%2FCommunity%2FForums#!category-topic/beagleboard/EECWGnvEjQo

**Comment by traversjames** [comment]
Looks like this has been approved for removal

**Comment by RobertCNelson** [comment]
@traversjames i'll patch it before thursday's snapshot, unless ti's beats me to it..
Regards,

**Comment by RobertCNelson** [comment]
now fixed as part of:
https://github.com/RobertCNelson/ti-linux-kernel-dev/commit/553822023931fe2cb02168d6edb547ac811c983a

this will be part of r19 on thursday..

**Comment by RobertCNelson** [comment]
nm pushing right now due to this commit in the ti diff:
https://github.com/RobertCNelson/ti-linux-kernel/commit/5bf93b966b88ff5aa668c767102d13a1ea1b6757

**Comment by RobertCNelson** [comment]
all pushed out, will be updating dtb-rebuilder/bb.org-overlays in a bit, but safe to close this..
