### ISSUE TITLE
SPI: length of word only power of two

### ISSUE THREAD

**Issue by kamtar** [beagleboard/linux#75]
Hello,
Why it is not possible to use any word length? Lot of SPI modules are able to work with it. 
https://github.com/beagleboard/linux/blob/master/drivers/spi/spi.c#L1859

Could someone propose some easy workaround how to use SPI with odd number of bits in word?

**Comment by djhenjin** [comment]
It is likely that most other SPI modules are indeed actually enforcing a proper word limit for transfers, and are just abstracting that fact away by padding the requested transmission to be a multiple of a power of 2 bits. 


 "Many SPI chips only support messages that are multiples of 8 bits. Such chips can not interoperate with the JTAG or SGPIO protocols, or any other protocol that requires messages that are not multiples of 8 bits." Source: https://en.wikipedia.org/wiki/Serial_Peripheral_Interface_Bus#Standards
