### ISSUE TITLE
Not able to get uboot promplt., getting "CCCC" on minicom terminal.

### ISSUE THREAD

**Issue by goudapatil** [beagleboard/linux#80]
Hi,

I was trying to boot BBB over tftp, but am not getting tftp boot.
I am getting "CCCC" on minicom terminal whenever I press reset button. Is the eMMC/uboot partition got corrupted ? 
Please help in getting the uboot prompt. 

Thanks,
Y M Patil

**Comment by RobertCNelson** [comment]
@goudapatil correct, the bootrom isn't finding the MLO file in either: dd'ed to the mbr or in the first fat partition..

Reflash..
